### ISSUE TITLE
Error: Cannot find module 'buffer/'

### ISSUE THREAD

**Issue by yuwade** [zhaojunlike/netty-snappy-framed#1]
Require stack:
- D:\WorkPlace\node\node_modules\netty-snappy\index.js
- D:\WorkPlace\node\netty通信.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:681:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:16:16)[39m
    at Object.382 (D:\WorkPlace\node\node_modules\[4mnetty-snappy[24m\index.js:1170:24)
    at i (D:\WorkPlace\node\node_modules\[4mnetty-snappy[24m\index.js:23:21)
    at D:\WorkPlace\node\node_modules\[4mnetty-snappy[24m\index.js:26:24
    at Object.226.225 (D:\WorkPlace\node\node_modules\[4mnetty-snappy[24m\index.js:586:23)
    at i (D:\WorkPlace\node\node_modules\[4mnetty-snappy[24m\index.js:23:21)
    at D:\WorkPlace\node\node_modules\[4mnetty-snappy[24m\index.js:26:24 {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'D:\\WorkPlace\\node\\node_modules\\netty-snappy\\index.js'[39m,
    [32m'D:\\WorkPlace\\node\\netty通信.js'[39m
  ]
}

**Comment by gtsigner** [comment]
考虑接入buffer库

**Comment by yuwade** [comment]
PS D:\WorkPlace\node> node
Welcome to Node.js v12.3.1.
Type ".help" for more information.
> require('buffer')
{
  Buffer: [Function: Buffer] {
    poolSize: 8192,
    from: [Function: from],
    of: [Function: of],
    alloc: [Function: alloc],
    allocUnsafe: [Function: allocUnsafe],
    allocUnsafeSlow: [Function: allocUnsafeSlow],
    isBuffer: [Function: isBuffer],
    compare: [Function: compare],
    isEncoding: [Function: isEncoding],
    concat: [Function: concat],
    byteLength: [Function: byteLength],
    [Symbol(kIsEncodingSymbol)]: [Function: isEncoding]
  },
  SlowBuffer: [Function: SlowBuffer],
  transcode: [Function: transcode],
  kMaxLength: 2147483647,
  kStringMaxLength: 1073741799,
  constants: { MAX_LENGTH: 2147483647, MAX_STRING_LENGTH: 1073741799 },
  INSPECT_MAX_BYTES: [Getter/Setter]
}
buffer 库是本身自带的

**Comment by yuwade** [comment]
382: [function (e, t, n) {
        const buffer = require('buffer/');
        t.exports = buffer;
    }, {}],

 require('buffer/');  多了一个/

**Comment by yuwade** [comment]
npm install buffer
就可以解决了
